@url = http://localhost:3000/api

### Usuarios
# Obtener todos los usuarios
GET {{url}}/users

#####################
##### Profesores ####
#####################

# Obtener un profesor por ID
GET {{url}}/profesores/1
Content-Type: application/json

###
# Registrar un nuevo profesor
POST {{url}}/profesores/registro
Content-Type: application/json

{
    "usuario": {
        "nombre": "Juan",
        "apellidos": "Pérez",
        "email": "juan.perez@example.com",
        "password": "Password123",
        "foto": "http://example.com/profile.jpg",
        "activo": true
    },
    "profesor": {
        "precio_hora": 20,
        "localizacion": "Madrid",
        "telefono": "123456789",
        "meses_experiencia": 36,
        "validado": false
    },
    "materias": [1, 2, 3]
}

###
# Actualizar un profesor existente
PUT {{url}}/profesores/1
Content-Type: application/json

{
    "usuario": {
        "nombre": "Juan",
        "apellidos": "Pérez",
        "email": "juan.perez@example.com",
        "password": "NewPassword123",
        "foto": "http://example.com/updated_profile.jpg",
        "activo": true
    },
    "profesor": {
        "precio_hora": 25,
        "localizacion": "Barcelona",
        "telefono": "987654321",
        "meses_experiencia": 48,
        "validado": true
    },
    "materias": [1, 3]
}

#####################
###### Alumnos ######
#####################

# Obtener un alumno por ID
GET {{url}}/alumnos/1

# Registrar un nuevo alumno
POST {{url}}/alumnos/registro
Content-Type: application/json

{
  "nombre": "Lucia",
  "apellidos": "Gonzalez",
  "email": "lucia@email.com",
  "password": "Password123",
  "foto": "https://student-image-url.jpg"
}

# Actualizar un alumno existente
PUT {{url}}/alumnos/1
Content-Type: application/json

{
  "nombre": "Lucia",
  "apellidos": "Gonzalez",
  "email": "lucia@email.com",
  "password": "NewPassword123",
  "foto": "https://new-student-image-url.jpg",
  "activo": true
}

#####################
###### Materias #####
#####################

# Obtener todas las materias
GET {{url}}/materias

# Obtener materias asignadas a un profesor por ID de profesor
GET {{url}}/materias/profesor-materias/1



###
POST {{url}}/login
Content-Type: application/json

{
  "email": "juan.perez@example.com",
  "password": "Password123"
}

#####################
###### Admin ########
#####################


# Activar o desactivar un alumno
PUT {{url}}/alumnos/1/activar
Content-Type: application/json

{
  "activo": true
}


# Validar o desvalidar un profesor
PUT {{url}}/profesores/1/validar
Content-Type: application/json

{
  "validado": true
}

