@url = http://localhost:3000/api

#####################
###### Usuarios #####
#####################

# Obtener todos los usuarios
GET {{url}}/usuarios

#####################
##### Profesores ####
#####################

## Listar Profesores
GET {{url}}/profesores
Content-Type: application/json

###

# Obtener un profesor por ID
GET {{url}}/profesores/54
Content-Type: application/json

#####################
###### Alumnos ######
#####################

## Listar Alumnos
GET {{url}}/alumnos
Content-Type: application/json

###

# Obtener un alumno por ID
GET {{url}}/alumnos/2
Content-Type: application/json


#####################
###### Materias #####
#####################

# Obtener todas las materias
GET {{url}}/materias
Content-Type: application/json

###

# Obtener materias asignadas a un profesor por ID de profesor
GET {{url}}/materias/profesor-materias/1
Content-Type: application/json

#####################
###### Admin ########
#####################

# Activar o desactivar un usuario
PUT {{url}}/usuarios/activar/2
Content-Type: application/json
Authorization: 

{
  "activo": false
}

###
# Validar o desvalidar un profesor
PUT {{url}}/profesores/validar/1
Content-Type: application/json
Authorization: 

{
  "validado": true
}

###
# Registrar un administrador
POST {{url}}/usuarios/registrarAdmin
Content-Type: application/json

{
  "nombre": "Usuario3",
  "apellidos": "Administrador",
  "email": "carrascogonzalezarturo@gmail.com",
  "password": "Admin123*",
  "activo": 1
}





#####################
###### Mensajes ######
#####################

###
#obtener mensajes entre 2 usuarios
GET {{url}}/mensajes/14/2


###
#enviar mensaje
POST {{url}}/mensajes/enviar
Content-Type: application/json

{
  "emisor_id": 7,
  "destinatario_id": 1,
  "asunto": "dsf",
  "contenido": "hola sdfgdffg"  
}


###
#marcar leido
patch  {{url}}/mensajes/418
Content-Type: application/json

{
  "leido": 1
}

###
#obtener mis alumnos por mi id
GET {{url}}/mensajes/misalumnos/4

###
#obtener mis profesores por mi id
GET {{url}}/mensajes/misprofesores/2